version: '3'

services:
  app:
    build: .
    container_name: symfony-example_app
    restart: on-failure
    volumes:
      - ./:/app
    working_dir: /app

  webserver:
    image: nginx:1.23.3
    restart: on-failure
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: mariadb:10.4.27
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'symfony_example_db'
    ports:
      - 3306:3306
    volumes:
      - database_data:/var/lib/mysql:rw

volumes:
  database_data:
