provider_list:
    path: /
    controller: App\Controller\ProviderListController::index

create_provider:
    path: /create
    controller: App\Controller\CreateProviderController::index

edit_provider_submitted:
    path: /edit/{id}/submitted
    controller: App\Controller\EditProviderController::editProvider

edit_provider:
    path: /edit/{id}
    controller: App\Controller\EditProviderController::index
